target_sources(
  obs-studio
  PRIVATE
    docks/OBSDock.cpp
    docks/OBSDock.hpp
    docks/TempestControlDeck.cpp
    docks/TempestControlDeck.hpp
    docks/TempestCommandMatrix.cpp
    docks/TempestCommandMatrix.hpp
)
